// <auto-generated />
using System;
using FinTracker.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228130846_Presentation_Categories")]
    partial class Presentation_Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinTracker.Domain.Presentation.Model.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Presentation_Categories");

                    b.ToTable("Categories", "presentation");
                });

            modelBuilder.Entity("FinTracker.Domain.Transaction.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Transaction_Categories");

                    b.ToTable("Categories", "transaction");
                });

            modelBuilder.Entity("FinTracker.Domain.Transaction.Model.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Transaction_Transactions");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions", "transaction");
                });

            modelBuilder.Entity("FinTracker.Domain.Presentation.Model.Category", b =>
                {
                    b.OwnsOne("FinTracker.Domain.Presentation.Model.CategoryAppearance", "Appearance", b1 =>
                        {
                            b1.Property<string>("CategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Color");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories", "presentation");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("FinTracker.Domain.Presentation.Model.EntityInformation", "Information", b1 =>
                        {
                            b1.Property<string>("CategoryId")
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Description");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Title");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories", "presentation");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Appearance")
                        .IsRequired();

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("FinTracker.Domain.Transaction.Model.Transaction", b =>
                {
                    b.HasOne("FinTracker.Domain.Transaction.Model.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FinTracker.Domain.Transaction.Model.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision")
                                .HasColumnName("MoneyAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MoneyCurrency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", "transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
